### ISSUE TITLE
train_tacotron.py 실행시 오류가 나요.

### ISSUE THREAD

**Issue by luhavis** [hccho2/Tacotron-Wavenet-Vocoder#3]
```
Traceback (most recent call last):
  File "train_tacotron.py", line 308, in <module>
    main()
  File "train_tacotron.py", line 305, in main
    train(config.model_dir, config)
  File "train_tacotron.py", line 146, in train
    train_feeder.loss_coeff,is_randomly_initialized=is_randomly_initialized)
  File "/data/Tacotron-Wavenet-Vocoder/tacotron/tacotron.py", line 185, in initialize
    for idx, cell in enumerate(decoder_rnn_init_states):
TypeError: 'NoneType' object is not iterable
```

이런오류가 나면서 실행이 안되는데 어떻게 해야될까요?

**Comment by hccho2** [comment]
num_speakers 값을 확인해보세요.

**Comment by luhavis** [comment]
감사합니다. 잘 해결했습니다
